#version: '3.8'

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.1
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINERS=1
      - EVENTS=1
      - NETWORKS=1
      - IMAGES=1
      - POST=1
      - PING=1
      - EXEC=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      # - dockflare-internal
      - docker-socket-proxy-net

  cloudflared-net-init:
    image: docker:cli
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-tcp://docker-socket-proxy:2375}
    command:
      - sh
      - -c
      - |
        echo "Checking if Network cloudflare-net exists..."
        if [ -z "$(docker network ls -f name=cloudflare-net -q)" ]; then
          echo "Network cloudflare-net does not exist, creating..."
          docker network create cloudflare-net
          echo "Network cloudflare-net created."
        else
          echo "Network cloudflare-net exists, skipping creation."
        fi
        echo "Network cloudflare-net check complete"
    restart: "no"
    depends_on:
      docker-socket-proxy:
        condition: service_started
    networks:
      - docker-socket-proxy-net

  dockflare-agent:
    # image: alplat/dockflare-agent:latest
    image: dockflare-agent:local
    container_name: dockflare-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-tcp://docker-socket-proxy:2375}
      - DOCKFLARE_API_KEY=${DOCKFLARE_API_KEY}
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CF_ACCESS_CLIENT_ID=${CF_ACCESS_CLIENT_ID}
      - CF_ACCESS_CLIENT_SECRET=${CF_ACCESS_CLIENT_SECRET}
    volumes:
      - ${DOCKFLARE_DATA_PATH}:/app/data
    depends_on:
      docker-socket-proxy:
        condition: service_started
      cloudflared-net-init:
        condition: service_completed_successfully
    networks:
      - cloudflare-net
      - dockflare-internal
      - docker-socket-proxy-net

  dockflare-agent-init:
    image: alpine:3.20
    command: ["sh", "-c", "echo 'checking permissions...' && chown -R ${DOCKFLARE_UID:-65532}:${DOCKFLARE_GID:-65532} /app/data"]
    volumes:
      - ${DOCKFLARE_DATA_PATH}:/app/data
    networks:
      - dockflare-internal
    restart: "no"

# volumes:
#   agent_data:

networks:
  cloudflare-net:
    name: cloudflare-net
  dockflare-internal:
    name: dockflare-internal
  docker-socket-proxy-net:
    name: docker-socket-proxy-net
