version: '3.8'

# Simple Docker Swarm deployment for DockFlare Agent
# This version assumes you have a secure Swarm cluster setup

services:
  dockflare-agent:
    image: alplat/dockflare-agent:latest
    environment:
      - DOCKFLARE_MASTER_URL=${DOCKFLARE_MASTER_URL}
      - DOCKFLARE_API_KEY=${DOCKFLARE_API_KEY}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_MODE=swarm
      - AGENT_DISPLAY_NAME=${AGENT_DISPLAY_NAME:-Swarm Node}
      - CLOUDFLARED_IMAGE=${CLOUDFLARED_IMAGE:-cloudflare/cloudflared:2025.9.0}
      - CLOUDFLARED_NETWORK_NAME=cloudflare-net
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent_data:/app/data
    networks:
      - cloudflare-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: unless-stopped

volumes:
  agent_data:

networks:
  cloudflare-net:
    driver: overlay
    attachable: true
    external: true